### PR TITLE
Release 0.2.5

### PR DESCRIPTION
**Pull request by HeroicKatora**
Replaces #237 

Since we do releases based on the feature branch itself (not the automatic merge, as it's unnnamed and potentially different) rebased this on master and pushed. Originally, I wanted to push this to the fork but accidentally pushed `master`, which auto-closed the through github. And without an active PR I'm no longer allowed to update the branch / undo that mistake :smile:

### CODE REVIEW

**Comment by HeroicKatora** [comment]
@gents83 sorry for the confusion.

**Comment by HeroicKatora** [comment]
And thank you for the release-notes and metadata bump :)

**Comment by gents83** [comment]
@HeroicKatora may I ask you to integrate it also in image pls?

**Comment by HeroicKatora** [comment]
There's no need to do it explicitly. It's compatible with the current spec (`^0.2.1`) and all it should take is a `cargo update` to renew the dependency. Let me know if there's an issue keeping this from working.

**Pull request merged**
