### PR TITLE
Bugfix non interleaved mcus

### PR DESCRIPTION
**Pull request by quilan1**
As detailed in the commits, the issue had to do with the way the old code treated MCUs in non-interleaved streams, with channels having a greater-than-1 sampling factor. In a non-interleaved stream, MCUs should be treated as single blocks instead of as the group of HxV blocks.

Future work might be considered to simplify the coding of batching rows together for the worker threads; currently it only accepts the full HxV set of blocks for a 'row', instead of an image row, and I didn't touch that code.

Solves #173 and addresses #89

### CODE REVIEW

**Comment by quilan1** [comment]
It occurs to me that the created jpeg file causes an error (bad huffman decode), not a panic; would this be better placed in the reftest images?

**Comment by HeroicKatora** [comment]
Yes, `crashtest` is for regressions that previously panicked and ignores the result. If you want to test success or a particular decoding response then the reftests are the appropriate place.

**Review by HeroicKatora — APPROVED** [review]
Mental note: At some future point we should change the `as u16` casts to `u16::from` where applicable because it makes it clear that they are lossless. I did stumble on this in the review.

**Comment by HeroicKatora** [comment]
Thank you!

**Pull request merged**
