### PR TITLE
Add support for extracting the ICC profile.

### PR DESCRIPTION
**Pull request by jrmuizel**

### CODE REVIEW

**Review by HeroicKatora — COMMENTED** [review]
Nice job overall and thanks for the reference comment, I just have some style nits.

**Review by HeroicKatora — APPROVED** [review]

**Comment by jrmuizel** [comment]
What needs to happen for this to get merged?

**Comment by HeroicKatora** [comment]
Any maintainer pressing the merge button :) Which often happens at the end of a week in case there might be outstanding comments.

**Comment by jrmuizel** [comment]
Perfect. Thanks!

**Pull request merged**
