### PR TITLE
fix clippy::into_iter_on_array error in decoder

### PR DESCRIPTION
**Pull request by scottmcm**
[Rust is trying to add `IntoIterator` for arrays](https://github.com/rust-lang/rust/pull/65819#issuecomment-547775045), which would break this.  So might as well do it the way that's forward-compatible and also shorter.

### CODE REVIEW

**Comment by scottmcm** [comment]
CI failure doesn't look like the fault of this change:
> failed to parse manifest at `/home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/cfg-if-0.1.10/Cargo.toml`

**Comment by CryZe** [comment]
Looks like rayon isn't actually compatible with 1.28 anymore (due to some indirect dependency on the latest cfg-if).

**Comment by lovasoa** [comment]
Maybe `Cargo.lock` should be committed...

**Comment by CryZe** [comment]
Nah, you don't commit Cargo.lock for libraries. Then CI would pass but it would still fail to build on 1.28 for everyone depending on this crate.

**Comment by LukasKalbertodt** [comment]
@fintelia Do you think this fix can be released with a minor version bump (i.e. 0.1.17)? That would be really great, as `jpeg-decoder` caused 290 other crates to regress due to this. That's the second most regression caused after `colored`.

**Comment by fintelia** [comment]
@LukasKalbertodt 0.1.17 has now been published.

**Pull request merged**
